# Site settings
title: Ning Xie
description: A blog about lorem ipsum dolor sit amet
baseurl:
url: https://ningxie1991.github.io/

# User settings
username: Ning Xie
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: ningxie1991@gmail.com
github_username:  ningxie1991

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
