# Site settings
title: Ning Xie
description: Portfolio, Personal Blog
baseurl:
url: https://ningxie1991.github.io/
repository: ningxie1991/ningxie1991.github.io

components:
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 3
        
# User settings
username: Ning Xie
user_description: I am an experienced software engineer who constantly seeks out innovative solutions to everyday problems. In my five years in the FinTech industry, I have honed my collaboration skills, web application development practices and analytical thinking in a dynamic global working environment. Currently I am pursuing a master's degree in People-Oriented Computing at the University of Zurich with a focus on Human-Computer Interaction and Artificial Intelligence. My thesis topic is on quantifying the trustworthiness level of federated machine learning models. I look forward to apply my past industry experience and improved knowledge from my master’s studies in the next professional role within the digital innovation industry.
user_title: Software Engineer
email: ningxie1991@gmail.com
github_username:  ningxie1991

plugins:
    - jekyll-github-metadata
    
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
