# Site settings
title: Ning Xie
description: Portfolio, Personal Blog
baseurl:
url: https://ningxie1991.github.io/
repository: ningxie1991/ningxie1991.github.io

components:
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 3
        
# User settings
username: Ning Xie
user_description: I am an experienced software engineer with a solid background in computer science and seven years in the tech industry. I am dedicated to crafting elegant solutions, writing clean code, exploring innovative approaches and learning new skills. Throughout my career, I have built a strong focus on frontend development and backend solution design, as well as the ability to collaborate effectively with diverse stakeholders and fellow engineers in agile environments. Currently I am exploring GenAI topics as well. Passionate about frontend development and technology, I am eager to leverage my expertise and enthusiasm in my next role within the innovation industry.
user_title: Software Engineer
email: ningxie1991@gmail.com
github_username:  ningxie1991

plugins:
    - jekyll-github-metadata
    
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
