# Site settings
title: Ning Xie
description: Portfolio, Personal Blog
baseurl:
url: https://ningxie1991.github.io/
repository: ningxie1991/ningxie1991.github.io

components:
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 3
        
# User settings
username: Ning Xie
user_description: I am an experienced full-stack software engineer who constantly seeks out innovative solutions to everyday problems. In my five years in the FinTech industry, I have matured my collaboration skills, software engineering practices and analytical thinking in a dynamic global working environment. Currently I am pursuing a master's degree at the University of Zurich with a focus in Human-Computer Interaction and Artificial Intelligence.
user_title: Software Engineer
email: ningxie1991@gmail.com
github_username:  ningxie1991

plugins:
    - jekyll-github-metadata
    
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
